@host = localhost
@port = 3333
@url = http://localhost:3333

### Create Student
POST {{url}}/create HTTP/1.1
Content-Type: application/json

{
  "name": "John",
  "lastname": "Doe",
  "course": "Computer Science",
  "github": "John-Doe",
  "email": "johndoe4@teste.com",
  "hardskills": ["Node", "Rust"],
  "softskills": ["Smart conversation", "Flexibal"],
  "projects": ["Web Site", "Web Scrapping"]
}

### Get Student
GET {{url}}/get-student/a666a74e-7839-4c8e-8328-f5092786c0eb HTTP/1.1

### Get All Student
GET {{url}}/get-all HTTP/1.1