version: '3.8'

services:
  postgres:
    container_name: fastify-clean-architecture
    image: postgres
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: ejsite
        PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres